name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Usa el runner auto-hospedado
    strategy:
      matrix:
        runner: ["samir","Jesus","cristian","andy"]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Deploy application #comentrai
      run: |
        # Comandos para desplegar tu aplicación
        pm2 reload WebPage
        
