name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Usa el runner auto-hospedado

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Check git status
      run: |
        cd ../Fastapi-MySQL/WebPage
        git status
    - name: Fetch and Reset to Latest
      run: |
        cd ../Fastapi-MySQL/WebPage
        git fetch origin
        git reset --hard origin/main

    - name: Deploy application
      run: |
        # Comandos para desplegar tu aplicación
        cd ../Fastapi-MySQL/WebPage
        git pull 
        pm2 reload Webpage
         
