name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, linux]  # Usa el runner auto-hospedado

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup environment
      run: |
        # Navegar al directorio del proyecto
        cd Fastapi-MySQL/WebPage
        
        # Instalar dependencias y preparar el entorno (ajusta según tu necesidad)
        sudo apt-get update
        sudo apt-get install -y git

    - name: Deploy application
      run: |
        # Comandos para desplegar tu aplicación
        cd /Fastapi-MySQL/WebPage
        git pull origin main
         
