name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Usa el runner auto-hospedado

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Deploy application #comentrai
      run: |
        # Comandos para desplegar tu aplicación
        cd Fastapi-MySQL/Fastapi-MySQL/WebPage/Backend
        chmod +x refresh.sh
        ./refresh.sh
         
