name: Deploy to Testing

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: self-hosted  # Usa el runner auto-hospedado
    strategy:
      matrix:
        runner: ["testing"]  # Solo el runner llamado "testing"
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Deploy to testing environment
      run: |
        # Comandos para desplegar tu aplicación en el ambiente de pruebas
        pm2 reload WebPageTesting
